### ISSUE TITLE
Logo 

### ISSUE THREAD

**Issue by CaitlinCMON** [DecodedCo/brand.decoded.com#64]
We need to make some edits to this page 
https://brand.decoded.com/pages/logo[https://brand.decoded.com/pages/logo](url)

1. Under the _Use it_ title, the _Download the Logo_ isn't working. 

- Can this be fixed easily? 
- Where should it be linking to?
- Could we link it to a folder on the G Drive that has all the different logo formats?
- Let me know and can create the folder and send you the link.

2. Please may we edit the _Use it _ section so that it reads:

To send logos to a client or use them in your own documents, Download the Logo.

Always use CMYK files for print products and RGB files for use on screen. For GDocs, use RGB files. Most Google Document Templates already have logos in them.

3. Leave the code section - but if you can check that the code works that would be great.

**Comment by amadeuspzs** [comment]
@CaitlinCMON if you can provide the updated link to the G Drive folder with Logos can you share here and I'll update

**Comment by amadeuspzs** [comment]
2. and 3. complete

**Comment by CaitlinCMON** [comment]
Thanks @amadeuspzs lets use this folder and see how folk get on https://drive.google.com/drive/folders/10v9pr6M0tITWkDufyybN5JRapd4eJ9cU
