### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by CaitlinCMON** [DecodedCo/brand.decoded.com#67]
We can keep alot of this - we just need to edit the template links and take away all of the links that aren't relevant anymore. The screencasts for Moo business cards are old now so let's remove for now. We can add these if we have alot 

TITLE: Templates

BODY: All the new brand templates are stored on the shared [Decoded Templates Drive](https://drive.google.com/drive/folders/0AE96BBcjg4gvUk9PVA)

New templates are added as they are designed. 

All templates are read-only. Open the template and select File -> Make a copy... to edit it. Then select File -> Move to Folder... to store it in an appropriate location on the drive. (then insert the image) 

**Template Name                     Link**

A4 Doc                                   [G Docs](https://docs.google.com/document/d/1IIWHU6XroNKtPH6VZWcau17YKr9-lib9U1F0b4MdEOM/edit)

Email Signature                      [Email Generator  ](http://clients.gregtilleystudio.com/decoded/signature/generator.html)

Business Cards                      [Order on moo.com](https://www.moo.com/mbs/products/business-cards)

**Comment by amadeuspzs** [comment]
Updated - not sure which templates you wanted deleted in addition to those above - can you check https://brand.decoded.com/pages/templates @CaitlinCMON

**Comment by CaitlinCMON** [comment]
Thanks @amadeuspzs 

Please delete 
- Advanced layout 
- Team bios
- Agenda template 
- Feedback template

**Comment by CaitlinCMON** [comment]
@amadeuspzs Dan and I are launching the new templates today at the company meeting. Therefore we need the link for the doc changing and the deck option to be included so the templates links looks as follows:

A4 Doc [G Docs](https://drive.google.com/open?id=1dVjp6ApzDM6e9cAwsq3n0kJVDpYGJ5jEEBOkDEj5ILI)

Presentation Deck [G Docs](https://drive.google.com/open?id=1vzSN7-cjvp0zYIYQNL6GGrcp2KQD09Hx0XGr4IrbirU)

Email Signature[ Email Generator](http://clients.gregtilleystudio.com/decoded/signature/generator.html)

Business Cards Order on [moo.com](https://www.moo.com/m4b/account/login?mbs_target=https%3A%2F%2Fwww.moo.com%2Fmbs%2Fproducts%2Fbusiness-cards&sig=69ad2a5d049bcb851cb5a1c0e5d11094e72f846ec315ef525b4ec74fb25f5b5c)
