### ISSUE TITLE
Photos 

### ISSUE THREAD

**Issue by CaitlinCMON** [DecodedCo/brand.decoded.com#69]
Please may we delete the team headshots as we are are not licensed to use these anymore. 

For the stock photos do we need to use tumbler or can I just save the photos that we want folk to use?

**Comment by amadeuspzs** [comment]
1. Complete
2. Yes please @CaitlinCMON can you share the Google Drive folder and I'll udpate

**Comment by CaitlinCMON** [comment]
Thanks @amadeuspzs please use this link https://drive.google.com/drive/folders/1H4zKsVv6LIgTyTH2CUQ8Lnb0zcQIWbLp
