### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by CaitlinCMON** [DecodedCo/brand.decoded.com#70]
@amadeuspzs Please may we add two more templates:

Feedback Report  [G Docs](https://drive.google.com/open?id=1v9jb4iGVagv6p-6lZ9HtH-YK-8SnZSaBoCuh0GqrP0Y)

Sign In Sheet   [G Docs](https://drive.google.com/open?id=1qwLKa517tR4u7iTgO6vcRU5QVUdVjTWNDVP0NlUA82k)

**Comment by CaitlinCMON** [comment]
@amadeuspzs Please may we add another template:

Basic Doc A4 Landscape [G Docs](https://drive.google.com/open?id=11rYAvKavatODwqCMoIY_01LU7l7_oV64Z7sCgU3yysc)

**Comment by Peritract** [comment]
Solved.
